### ISSUE TITLE
Removing empty quotes

### ISSUE THREAD

**Issue by tomsterritt** [rstacruz/css-condense#10]
Is there any way to prevent empty quotes being removed? 

For example using pseudo elements, ```content: "";``` becomes ```content:;```

**Comment by ben-eb** [comment]
I can't reproduce this.

```css
h1:after {
    content: '';
}
```

Is compressed correctly to:

```css
h1:after{content:''}
```

I tried both styles of quotes, too...
