### ISSUE TITLE
add option to remove blank lines wit --no-compress

### ISSUE THREAD

**Issue by bouks** [rstacruz/css-condense#11]
Hi.
Great job!

Is it possible to add an option like "-no-blank-lines"
Actual --no-compress do :

```css
h1 {
  background: none;
}

a {
  padding: 0.30em;
}
```

and wanted is :

```css
h1 {
  background: none;
}
a {
  padding: 0.30em;
}
```
