### ISSUE TITLE
Multiple font-face definitions should not be merged

### ISSUE THREAD

**Issue by geirlandro** [rstacruz/css-condense#2]
css-condense is merging multiple font-face definitions.
Each webfont needs to be in a separate `@font-face {}` for it to work.

So if I have this:

``` css
@font-face {
  font-family: 'font1';
  src: url('font1.eot?') format('eot'), url('font1.woff') format('woff'), url('font1.ttf') format('truetype');
}
@font-face {
  font-family: 'font2';
  src: url('font2.eot?') format('eot'), url('font2.woff') format('woff'), url('font2.ttf') format('truetype');
}
```

cssc condenses it to

``` css
@font-face{font-family:font1;font-family:font2;src:url(font1.eot?) format('eot'),url("font1.woff") format('woff'),url("font1.ttf") format('truetype');src:url(font2.eot?) format('eot'),url("font2.woff") format('woff'),url("font2.ttf") format('truetype')}
```

When it should be:

``` css
@font-face{font-family:font1;src:url(font1.eot?) format('eot'),url("font1.woff") format('woff'),url("font1.ttf") format('truetype')}
@font-face{font-family:font2;src:url(font2.eot?) format('eot'),url("font2.woff") format('woff'),url("font2.ttf") format('truetype')}
```
